# -*- coding: utf-8 -*-
"""RL tutorial - MULTI AGENT - REINFORCE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EG6q27kk7t2Y1BOed3QJ2X_G-YtZDA7Y

# 🪙 Training TWO Agents on the Coin Game

**Summer School Tutorial — Multi-Agent Reinforcement Learning**

In this notebook we will:
1. Build a simple **multi-agent grid-world** (the Coin Game)
2. Train agents with **REINFORCE** — the simplest working policy gradient
3. Visualize what the agents learn to do

---

### The Coin Game

Two agents (🔴 Red, 🔵 Blue) move on a small grid. There are two coins — a red coin and a blue coin. Each step:
- An agent that steps on **its own coin** gets **+1** reward
- An agent that steps on the **other's coin** gets **-1** reward
- Collected coins respawn in random positions

Each agent's observation is a flat vector encoding the grid positions of both agents and both coins.
"""

!pip install jax jaxlib equinox optax chex --quiet

import jax
import jax.numpy as jnp
import equinox as eqx
import optax
import chex
import csv
import copy
import os
import pickle
import numpy as np
import matplotlib.pyplot as plt
from jax import jit, lax
from typing import Tuple
from datetime import datetime
import functools

import matplotlib.patches as mpatches
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

jax.config.update("jax_enable_x64", False)
print("JAX version:", jax.__version__)
print("Devices:", jax.devices())

"""# ── 2. The Two-Player Coin Game ─────────────────

## 2.1. Modification of the Coin Game environment

Each agent sees itself as agent 0 (first layer of the State)
"""

@chex.dataclass
class TwoAgentState:
    pos_0:     jnp.ndarray
    pos_1:     jnp.ndarray
    coin_r:    jnp.ndarray
    coin_b:    jnp.ndarray
    step_count:int

# Five actions: right, left, down, up, stay
MOVES = jnp.array([
    [0,  1],   # right
    [0, -1],   # left
    [-1,  0],   # down
    [1, 0],   # up
    [0,  0],   # stay
])

class Policy(eqx.Module):
    """Two-layer MLP → action logits."""
    linear1: eqx.nn.Linear
    linear2: eqx.nn.Linear
    linear3: eqx.nn.Linear

    def __init__(self, obs_dim: int, n_actions: int, key):
        k1, k2, k3 = jax.random.split(key, 3)
        self.linear1 = eqx.nn.Linear(obs_dim,   64, key=k1)
        self.linear2 = eqx.nn.Linear(64,        64, key=k2)
        self.linear3 = eqx.nn.Linear(64, n_actions, key=k3)

    def __call__(self, obs):
        x = obs.astype(jnp.float32)
        x = jax.nn.tanh(self.linear1(x))
        x = jax.nn.tanh(self.linear2(x))
        x = self.linear3(x)
        return x

@eqx.filter_jit
def sample_action(policy, obs, key):
    """Sample an action and return its log-probability and probability."""
    logits   = policy(obs)
    action   = jax.random.categorical(key, logits)
    log_probs = jax.nn.log_softmax(logits)
    log_prob = log_probs[action]
    probs = jnp.exp(log_probs)
    prob = probs[action]
    return action, log_prob, prob

class TwoPlayerCoinGame:
    def __init__(self, grid_size: int = 3, episode_length: int = 100):
        self.grid_size = grid_size
        self.episode_length = episode_length
        self.agents = ["agent_0", "agent_1"]

    @functools.partial(jit, static_argnums=(0,))
    def _state_to_obs(self, state: TwoAgentState):
        g = self.grid_size

        # Red perspective: [self=red, enemy=blue, own_coin=red, enemy_coin=blue]
        grid_r = jnp.zeros((g, g, 4), dtype=jnp.float32)
        grid_r = grid_r.at[state.pos_0[0], state.pos_0[1], 0].set(1.0)
        grid_r = grid_r.at[state.pos_1[0], state.pos_1[1], 1].set(1.0)
        grid_r = grid_r.at[state.coin_r[0], state.coin_r[1], 2].set(1.0)
        grid_r = grid_r.at[state.coin_b[0], state.coin_b[1], 3].set(1.0)

        # Blue perspective: [self=blue, enemy=red, own_coin=blue, enemy_coin=red]
        grid_b = jnp.zeros((g, g, 4), dtype=jnp.float32)
        grid_b = grid_b.at[state.pos_1[0], state.pos_1[1], 0].set(1.0)
        grid_b = grid_b.at[state.pos_0[0], state.pos_0[1], 1].set(1.0)
        grid_b = grid_b.at[state.coin_b[0], state.coin_b[1], 2].set(1.0)
        grid_b = grid_b.at[state.coin_r[0], state.coin_r[1], 3].set(1.0)

        return {"agent_0": grid_r.flatten(), "agent_1": grid_b.flatten()}

    @functools.partial(jit, static_argnums=(0,))
    def reset(self, key: jnp.ndarray):
        # 4 uniquely sampled starting positions to prevent overlapping
        flat_idx = jax.random.choice(key, self.grid_size**2, shape=(4,), replace=False)
        def to_2d(idx): return jnp.array([idx // self.grid_size, idx % self.grid_size])

        state = TwoAgentState(
            pos_0=to_2d(flat_idx[0]), pos_1=to_2d(flat_idx[1]),
            coin_r=to_2d(flat_idx[2]), coin_b=to_2d(flat_idx[3]),
            step_count=0
        )
        return self._state_to_obs(state), state

    @functools.partial(jit, static_argnums=(0,))
    def step(self, key: jnp.ndarray, state: TwoAgentState, actions: dict):
        new_pos_0 = (state.pos_0 + MOVES[actions["agent_0"]]) % self.grid_size
        new_pos_1 = (state.pos_1 + MOVES[actions["agent_1"]]) % self.grid_size

        r_gets_cr = jnp.all(new_pos_0 == state.coin_r)
        r_gets_cb = jnp.all(new_pos_0 == state.coin_b)
        b_gets_cb = jnp.all(new_pos_1 == state.coin_b)
        b_gets_cr = jnp.all(new_pos_1 == state.coin_r)

        # The Social Dilemma Rewards
        reward_r = (r_gets_cr * 1.0) - (r_gets_cb * 1.0)
        reward_b = (b_gets_cb * 1.0) - (b_gets_cr * 1.0)

        k1, k2 = jax.random.split(key)
        G = self.grid_size
        def respawn(keep_coin, rand_key):
            flat_keep = keep_coin[0] * G + keep_coin[1]
            valid = jnp.ones(G*G, dtype=jnp.float32).at[flat_keep].set(0.0)
            new_flat = jax.random.choice(rand_key, G*G, p=valid/valid.sum())
            return jnp.array([new_flat // G, new_flat % G])

        any_gets_cr = r_gets_cr | b_gets_cr
        any_gets_cb = r_gets_cb | b_gets_cb

        new_coin_r = jnp.where(any_gets_cr, respawn(state.coin_b, k1), state.coin_r)
        new_coin_b = jnp.where(any_gets_cb, respawn(new_coin_r, k2), state.coin_b)

        new_step = state.step_count + 1
        next_state = TwoAgentState(
            pos_0=new_pos_0, pos_1=new_pos_1,
            coin_r=new_coin_r, coin_b=new_coin_b,
            step_count=new_step
        )
        return self._state_to_obs(next_state), next_state, {"agent_0": reward_r, "agent_1": reward_b}, new_step >= self.episode_length

# ── Two Player Evaluation & Animation ────────────────────────────────────────

def run_two_player_episode(save_path, config, seed=42):
    with open(os.path.join(save_path, "models.pkl"), "rb") as f:
        models = pickle.load(f)

    policy_0 = models["agent_0"]
    policy_1 = models.get("agent_1", models["agent_0"])

    env = TwoPlayerCoinGame(config['GRID_SIZE'], config['EPISODE_LENGTH'])
    key = jax.random.PRNGKey(seed)
    obs, state = env.reset(key)

    frames  = [state]
    rewards = {'agent_0': [], 'agent_1': []}
    coins   = {'agent_0': {'red': [], 'blue': []}, 'agent_1': {'red': [], 'blue': []}}
    done = False

    while not done:
        old_rc, old_bc = state.coin_r, state.coin_b

        actions = {
            "agent_0": int(jnp.argmax(policy_0(obs["agent_0"]))),
            "agent_1": int(jnp.argmax(policy_1(obs["agent_1"])))
        }
        key, sk = jax.random.split(key)

        obs, state, rws, done = env.step(sk, state, actions)

        frames.append(state)
        rewards['agent_0'].append(float(rws['agent_0']))
        rewards['agent_1'].append(float(rws['agent_1']))

        # Track which coin each agent picked
        coins['agent_0']['red'].append(int(jnp.all(state.pos_0 == old_rc)))
        coins['agent_0']['blue'].append(int(jnp.all(state.pos_0 == old_bc)))
        coins['agent_1']['red'].append(int(jnp.all(state.pos_1 == old_rc)))
        coins['agent_1']['blue'].append(int(jnp.all(state.pos_1 == old_bc)))

    return frames, rewards, coins

def animate_two_agents(save_path, config, seed=42, interval_ms=520):
    frames, rewards, coins = run_two_player_episode(save_path, config, seed)
    G = config['GRID_SIZE']
    T = len(frames) - 1

    BG = '#13131a'; GRID_C = '#2a2a3a'
    RED_AG = '#ff4545'; RED_COIN = '#ff8080'
    BLUE_AG = '#4585ff'; BLUE_COIN = '#80b3ff'

    fig = plt.figure(figsize=(12, 5.5), facecolor=BG)
    gs  = fig.add_gridspec(1, 2, width_ratios=[1.25, 0.75], wspace=0.12)
    ax = fig.add_subplot(gs[0], facecolor=BG)
    ax.set_xlim(-0.5, G - 0.5); ax.set_ylim(-0.5, G - 0.5)
    ax.set_aspect('equal'); ax.invert_yaxis(); ax.set_xticks([]); ax.set_yticks([])
    for spine in ax.spines.values(): spine.set_edgecolor('#333')

    for r in range(G):
        for c in range(G):
            col = '#1a1a24' if (r+c)%2==0 else '#16161f'
            ax.add_patch(plt.Rectangle((c-.5, r-.5), 1, 1, color=col, zorder=0))
        ax.axhline(r - 0.5, color=GRID_C, lw=1, zorder=1)
        ax.axvline(r - 0.5, color=GRID_C, lw=1, zorder=1)

    rc_patch = plt.Circle((0,0), 0.28, color=RED_COIN, alpha=0.92, zorder=3)
    bc_patch = plt.Circle((0,0), 0.28, color=BLUE_COIN, alpha=0.92, zorder=3)
    ax.add_patch(rc_patch); ax.add_patch(bc_patch)

    rc_lbl = ax.text(0, 0, '$', ha='center', va='center', fontsize=11, color='white', fontweight='bold', zorder=4)
    bc_lbl = ax.text(0, 0, '$', ha='center', va='center', fontsize=11, color='white', fontweight='bold', zorder=4)

    ra_pt, = ax.plot([], [], '^', ms=22, color=RED_AG, zorder=5, markeredgecolor='white', markeredgewidth=1.2)
    ba_pt, = ax.plot([], [], '^', ms=22, color=BLUE_AG, zorder=5, markeredgecolor='white', markeredgewidth=1.2)

    # ── Initialize Trails ──
    TRAIL = 4
    r_trails = [ax.plot([], [], '-', color=RED_AG, alpha=0.13*(i+1), lw=2.5, zorder=2)[0] for i in range(TRAIL)]
    b_trails = [ax.plot([], [], '-', color=BLUE_AG, alpha=0.13*(i+1), lw=2.5, zorder=2)[0] for i in range(TRAIL)]

    # ── Coin Bars & Reward panel ──────────────────────────────────────────
    ax2 = fig.add_subplot(gs[1], facecolor=BG)
    ax2.set_title('Coins Collected & Total Reward', color='white', fontsize=11, pad=10)
    ax2.set_xlim(-0.5, 1.5)
    ax2.set_xticks([0, 1])
    ax2.set_xticklabels(['Red Agent', 'Blue Agent'], color='white', fontsize=11)
    ax2.set_ylim(0, config['EPISODE_LENGTH'] * 0.75)
    ax2.axhline(0, color='#444', lw=0.9)
    ax2.tick_params(axis='y', colors='#666')
    for spine in ax2.spines.values(): spine.set_edgecolor('#333')

    # Grouped bars for Red Agent
    bar_r_rc = ax2.bar([-0.15], [0], color=RED_COIN, alpha=0.9, width=0.25)[0]
    bar_r_bc = ax2.bar([0.15], [0], color=BLUE_COIN, alpha=0.9, width=0.25)[0]

    # Grouped bars for Blue Agent
    bar_b_rc = ax2.bar([0.85], [0], color=RED_COIN, alpha=0.9, width=0.25)[0]
    bar_b_bc = ax2.bar([1.15], [0], color=BLUE_COIN, alpha=0.9, width=0.25)[0]

    # Absolute rewards as floating text above the agents
    val_r = ax2.text(0, config['EPISODE_LENGTH']*0.65, 'Reward: +0', ha='center', color='white', fontsize=12, fontweight='bold')
    val_b = ax2.text(1, config['EPISODE_LENGTH']*0.65, 'Reward: +0', ha='center', color='white', fontsize=12, fontweight='bold')

    state_box = {
        'cum_r': 0., 'cum_b': 0.,
        'r_rc': 0, 'r_bc': 0,
        'b_rc': 0, 'b_bc': 0,
        'rh': [], 'bh': [] # Added history lists for the trails
    }

    def update(fi):
        if fi == 0:
            for k in state_box:
                if isinstance(state_box[k], list):
                    state_box[k].clear()
                else:
                    state_box[k] = 0

        st = frames[fi]

        rc_patch.center = (float(st.coin_r[1]), float(st.coin_r[0]))
        rc_lbl.set_position((float(st.coin_r[1]), float(st.coin_r[0])))
        bc_patch.center = (float(st.coin_b[1]), float(st.coin_b[0]))
        bc_lbl.set_position((float(st.coin_b[1]), float(st.coin_b[0])))

        ra_pt.set_data([float(st.pos_0[1])], [float(st.pos_0[0])])
        ba_pt.set_data([float(st.pos_1[1])], [float(st.pos_1[0])])

        # Update Trail Histories
        state_box['rh'].append((float(st.pos_0[1]), float(st.pos_0[0])))
        state_box['bh'].append((float(st.pos_1[1]), float(st.pos_1[0])))
        rh = state_box['rh']
        bh = state_box['bh']

        for i, trl in enumerate(r_trails):
            seg = rh[max(0, len(rh)-TRAIL+i): len(rh)-TRAIL+i+2]
            trl.set_data([s[0] for s in seg], [s[1] for s in seg]) if len(seg)>=2 else None

        for i, trl in enumerate(b_trails):
            seg = bh[max(0, len(bh)-TRAIL+i): len(bh)-TRAIL+i+2]
            trl.set_data([s[0] for s in seg], [s[1] for s in seg]) if len(seg)>=2 else None

        if fi > 0:
            state_box['cum_r'] += rewards['agent_0'][fi-1]
            state_box['cum_b'] += rewards['agent_1'][fi-1]
            state_box['r_rc']  += coins['agent_0']['red'][fi-1]
            state_box['r_bc']  += coins['agent_0']['blue'][fi-1]
            state_box['b_rc']  += coins['agent_1']['red'][fi-1]
            state_box['b_bc']  += coins['agent_1']['blue'][fi-1]

        # Update Bars
        bar_r_rc.set_height(state_box['r_rc'])
        bar_r_bc.set_height(state_box['r_bc'])
        bar_b_rc.set_height(state_box['b_rc'])
        bar_b_bc.set_height(state_box['b_bc'])

        # Update Text
        val_r.set_text(f"Reward: {state_box['cum_r']:+.0f}")
        val_b.set_text(f"Reward: {state_box['cum_b']:+.0f}")

        # Ensure *r_trails and *b_trails are unpacked and returned for blitting
        return (rc_patch, bc_patch, ra_pt, ba_pt, *r_trails, *b_trails,
                bar_r_rc, bar_r_bc, bar_b_rc, bar_b_bc, val_r, val_b)

    anim = FuncAnimation(fig, update, frames=len(frames), interval=interval_ms, blit=True)
    plt.tight_layout()
    return HTML(anim.to_jshtml())

"""---
## 2.2. Results — reward curves

**What to look for:**
- Agents at **+15** → cooperation (each collecting their own coin every step)
- Both agents near **0 or negative** → mutual defection
- One high, one low → one agent is consistently stealing
"""

CONFIG = {
    # Environment
    'GRID_SIZE':        4,
    'EPISODE_LENGTH':   100,    # steps per episode

    # Training
    'NUM_EPISODES':     1800,
    'GAMMA':            0.9,  # discount factor
    'LR':               3e-3,  # learning rate

    # Logging
    'SHOW_EVERY':       50,
}

latest_save_path = "./runs"

animate_two_agents(latest_save_path, CONFIG)

"""# ── 3. Multi-Agent Co-Training ─────────────────

Agents learn **independently** — each only sees its own rewards.
"""

def discounted_returns(rewards: list, gamma: float) -> jnp.ndarray:
    """Compute G_t = r_t + γ r_{t+1} + γ² r_{t+2} + ... for each t."""
    R, returns = 0.0, []
    for r in reversed(rewards):
        R = float(r) + gamma * R
        returns.insert(0, R)
    G = jnp.array(returns)
    # Normalize for stable gradients
    return (G - G.mean()) / (G.std() + 1e-8)


@jit
def reinforce_loss(policy, obs_batch, actions_batch, returns):
    # 1. Run the forward pass INSIDE the loss function
    logits = jax.vmap(policy)(obs_batch)

    # 2. Compute log probabilities for all actions
    log_probs_all = jax.nn.log_softmax(logits)

    # 3. Select the log probabilities of the actions actually taken
    log_probs = log_probs_all[jnp.arange(len(actions_batch)), actions_batch]

    # 4. Calculate the REINFORCE objective
    return -jnp.mean(log_probs * returns)

@eqx.filter_jit
def update_agent(policy, opt_state, optimizer, obs_batch, actions_batch, returns):
    # 1. Calculate gradients
    loss, grads = jax.value_and_grad(reinforce_loss)(policy, obs_batch, actions_batch, returns)
    # 2. Update optimizer state
    updates, new_opt_state = optimizer.update(grads, opt_state)
    # 3. Apply updates to the policy
    new_policy = optax.apply_updates(policy, updates)

    return new_policy, new_opt_state, loss

def train_multiagent(pretrained_path, config):
    print(f"Loading pretrained weights from: {pretrained_path}")
    env = TwoPlayerCoinGame(config['GRID_SIZE'], config['EPISODE_LENGTH'])

    # 1. Load the pretrained single-agent model
    with open(os.path.join(pretrained_path, "models.pkl"), "rb") as f:
        pretrained_models = pickle.load(f)
    pretrained_policy = pretrained_models["agent_0"]

    # 2. Clone it so both agents start highly capable, but learn independently
    policies = {
        "agent_0": copy.deepcopy(pretrained_policy),
        "agent_1": copy.deepcopy(pretrained_policy)
    }

    # 3. Initialize independent optimizers
    optimizers, opt_states = {}, {}
    for agent in env.agents:
        opt = optax.adam(config['LR'])
        optimizers[agent] = opt
        opt_states[agent] = opt.init(eqx.filter(policies[agent], eqx.is_array))

    history = []
    key = jax.random.PRNGKey(42)

    # Use integer division (//) to avoid TypeError
    for ep in range(config['NUM_EPISODES']):
        key, ep_key = jax.random.split(key)
        obs, state = env.reset(ep_key)

        traj = {ag: {'obs': [], 'actions': [], 'rewards': []} for ag in env.agents}

        # Track coins per agent for this episode
        ep_coins = {
            'agent_0': {'red': 0, 'blue': 0},
            'agent_1': {'red': 0, 'blue': 0}
        }

        done = False

        # ── Rollout ──
        while not done:
            key, k1, k2 = jax.random.split(key, 3)

            # Fast JIT-compiled action sampling
            a0, _, _ = sample_action(policies["agent_0"], obs["agent_0"], k1)
            a1, _, _ = sample_action(policies["agent_1"], obs["agent_1"], k2)
            actions = {"agent_0": a0, "agent_1": a1}

            for ag in env.agents:
                traj[ag]['obs'].append(obs[ag])
                traj[ag]['actions'].append(actions[ag])

            # Snapshot old coin positions before the step
            old_cr, old_cb = state.coin_r, state.coin_b

            key, step_key = jax.random.split(key)
            obs, next_state, rewards, done = env.step(step_key, state, actions)

            # Check who picked up what by comparing new positions to old coin locations
            a0_pos, a1_pos = next_state.pos_0, next_state.pos_1

            ep_coins['agent_0']['red']  += int(jnp.all(a0_pos == old_cr))
            ep_coins['agent_0']['blue'] += int(jnp.all(a0_pos == old_cb))

            ep_coins['agent_1']['red']  += int(jnp.all(a1_pos == old_cr))
            ep_coins['agent_1']['blue'] += int(jnp.all(a1_pos == old_cb))

            state = next_state

            for ag in env.agents:
                traj[ag]['rewards'].append(float(rewards[ag]))

        # ── Update ──
        for agent in env.agents:
            obs_b = jnp.stack(traj[agent]['obs'])
            actions_b = jnp.array(traj[agent]['actions'])
            returns = discounted_returns(traj[agent]['rewards'], config['GAMMA'])

            policies[agent], opt_states[agent], _ = update_agent(
                policies[agent], opt_states[agent], optimizers[agent], obs_b, actions_b, returns
            )

        ep_r0 = sum(traj['agent_0']['rewards'])
        ep_r1 = sum(traj['agent_1']['rewards'])

        # Save rewards and all 4 coin counters
        history.append((
            ep, ep_r0, ep_r1,
            ep_coins['agent_0']['red'], ep_coins['agent_0']['blue'],
            ep_coins['agent_1']['red'], ep_coins['agent_1']['blue']
        ))

        if ep % config['SHOW_EVERY'] == 0:
            print(f"MA Ep {ep:4d}  |  r_0={ep_r0:+.1f} (R:{ep_coins['agent_0']['red']} B:{ep_coins['agent_0']['blue']})  |  r_1={ep_r1:+.1f} (R:{ep_coins['agent_1']['red']} B:{ep_coins['agent_1']['blue']})")

    # ── Save Results ──
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    save_path = os.path.join(config.get("SAVE_DIR", "./runs"), f"multiagent_{timestamp}")
    os.makedirs(save_path, exist_ok=True)

    csv_path = os.path.join(save_path, "stats.csv")
    with open(csv_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["episode", "reward_agent_0", "reward_agent_1", "a0_red_coins", "a0_blue_coins", "a1_red_coins", "a1_blue_coins"])
        writer.writerows(history)

    with open(os.path.join(save_path, "models.pkl"), "wb") as f:
        pickle.dump(policies, f)

    print(f"\nDone! Co-trained models saved to: {save_path}")
    return policies, history, save_path

# Run the co-training loop using the previously saved single-agent path
ma_policies, ma_history, ma_save_path = train_multiagent(latest_save_path, CONFIG)

# ── 11. Co-Training Results ──────────────────────────────────────────────────

def plot_multiagent_rewards(history, window=50):
    # Unpack the 7-element tuples
    eps   = np.array([h[0] for h in history])
    r0    = np.array([h[1] for h in history])
    r1    = np.array([h[2] for h in history])
    a0_rc = np.array([h[3] for h in history])
    a0_bc = np.array([h[4] for h in history])
    a1_rc = np.array([h[5] for h in history])
    a1_bc = np.array([h[6] for h in history])

    def smooth(x):
        return np.convolve(x, np.ones(window)/window, mode='valid')

    BG = '#0f0f12'
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 5))
    fig.patch.set_facecolor(BG)

    # ── Subplot 1: Agent 0 (Red) ──
    ax1.set_facecolor(BG)
    ax1.plot(eps, r0, color='#ffffff', alpha=0.15, linewidth=0.7)
    ax1.plot(eps[:len(smooth(r0))], smooth(r0), color='#ffffff', linewidth=2.5, label='Total Reward')

    ax1.plot(eps, a0_rc, color='#ff4545', alpha=0.15, linewidth=0.7)
    ax1.plot(eps[:len(smooth(a0_rc))], smooth(a0_rc), color='#ff4545', linewidth=2.0, label='Red Coins (Coop)')

    ax1.plot(eps, a0_bc, color='#80b3ff', alpha=0.15, linewidth=0.7)
    ax1.plot(eps[:len(smooth(a0_bc))], smooth(a0_bc), color='#80b3ff', linewidth=2.0, label='Blue Coins (Steal)')

    ax1.axhline(0, color='#444', linestyle='--', linewidth=0.9)
    ax1.set_title('Agent 0 (Red) Behavior', color='white', fontsize=13, fontweight='bold')

    # ── Subplot 2: Agent 1 (Blue) ──
    ax2.set_facecolor(BG)
    ax2.plot(eps, r1, color='#ffffff', alpha=0.15, linewidth=0.7)
    ax2.plot(eps[:len(smooth(r1))], smooth(r1), color='#ffffff', linewidth=2.5, label='Total Reward')

    ax2.plot(eps, a1_bc, color='#80b3ff', alpha=0.15, linewidth=0.7)
    ax2.plot(eps[:len(smooth(a1_bc))], smooth(a1_bc), color='#80b3ff', linewidth=2.0, label='Blue Coins (Coop)')

    ax2.plot(eps, a1_rc, color='#ff4545', alpha=0.15, linewidth=0.7)
    ax2.plot(eps[:len(smooth(a1_rc))], smooth(a1_rc), color='#ff4545', linewidth=2.0, label='Red Coins (Steal)')

    ax2.axhline(0, color='#444', linestyle='--', linewidth=0.9)
    ax2.set_title('Agent 1 (Blue) Behavior', color='white', fontsize=13, fontweight='bold')

    # ── Formatting for both axes ──
    for ax in (ax1, ax2):
        ax.set_xlabel('Episode', color='#ccc', fontsize=11)
        ax.set_ylabel('Count / Reward', color='#ccc', fontsize=11)
        ax.tick_params(colors='#777')
        for spine in ax.spines.values(): spine.set_edgecolor('#333')
        ax.legend(facecolor='#1e1e24', edgecolor='#444', labelcolor='white', fontsize=9, loc='lower left')

    fig.suptitle('Independent REINFORCE Co-Training: The Tragedy of the Commons', color='white', fontsize=16, fontweight='bold', y=1.02)
    plt.tight_layout()
    plt.show()

plot_multiagent_rewards(ma_history)

# Animate the newly co-trained agents to see how their behavior shifted
animate_two_agents(ma_save_path, CONFIG)

"""---
## 4. Multi-Agent Adaptation: From Individual Learning to Collective Behavior

### What just happened?
During pretraining, our single agent learned a very simple, globally greedy heuristic: **all coins are good**. It optimized its individual cognition to navigate the grid and collect both Red and Blue coins for a constant stream of **+1** rewards.

However, when we clone this agent and drop two instances into the shared environment, the mechanics—and crucially, the rewards—change:
* Collecting your own coin yields **+1**.
* Collecting the other agent's coin yields **-1** to the collector.

Because both agents were taught to blindly collect everything they see, they immediately start picking up the wrong coins, actively punishing themselves. They must undergo an "unlearning" phase. This is no longer just about learning to navigate; it is about adapting an entrenched individual policy to new environmental rules where previously optimal actions are now harmful.

### Broader Dynamics in Multi-Agent Learning
While our current setup directly punishes agents for the "wrong" action—making it a straightforward adaptation problem—it serves as a stepping stone to much richer multi-agent phenomena:

* **Transfer Learning vs. Learning from Scratch:** The agents entered the shared environment highly capable of navigation but with the wrong objective. In deep reinforcement learning, unlearning a strong prior (like "all coins equal reward") sometimes takes longer than learning from scratch, as the network's weights must be pulled out of a deep local optimum.
* **Non-Stationarity and Co-Adaptation:** Unlike the single-agent case, the environment here is constantly shifting. As the Red agent learns to ignore Blue coins, the distribution of coins on the grid changes for the Blue agent. They are co-adapting, meaning each agent is chasing a moving target.
* **Social Influence and Social Dilemmas:** What if the rewards were slightly different? If grabbing the enemy's coin gave the collector **+1** but penalized the owner **-2**, the agents would face a true **Social Dilemma**. In that scenario, stealing is locally rational but globally destructive. Overcoming such dilemmas requires agents to account for their social influence on others, often necessitating algorithms that explicitly model opponent behavior or use centralized critics to foster genuine cooperation.

The leap from an isolated agent to a shared ecosystem is the core challenge of multi-agent reinforcement learning. It requires moving beyond simple environment-mapping toward policies that can interpret, adapt to, and ultimately coexist with other learning entities.
"""

